---
title: "Assignment 4"
author: "Shellby Johnson_Kristan Culbert"
date: "May 29, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tidyverse)

devtools::install_github("dill/beyonce") #use Beyonce style palette (found at: https://github.com/dill/beyonce)
library(beyonce) #yaaas

sector_emissions <- read_csv("HW4Data.csv")

```


#1 Regression of Marginal Cost of Abatement
```{r}

## Plotting the raw data to see how it looks 

#Plot A

carbon_plot_A <- ggplot(sector_emissions, aes(x = Abatement, y = MC_A)) +
  geom_point()
carbon_plot_A

#Plot B

carbon_plot_B <- ggplot(sector_emissions, aes(x = Abatement, y = MC_B)) +
  geom_point()
carbon_plot_B

#Plot C

carbon_plot_C <- ggplot(sector_emissions, aes(x = Abatement, y = MC_C)) +
  geom_point()
carbon_plot_C

#Plot D

carbon_plot_D <- ggplot(sector_emissions, aes(x = Abatement, y = MC_D)) +
  geom_point()
carbon_plot_D

```
Question #1
```{r}


# Linear model for A

lm_A <- lm(formula = MC_A ~ Abatement, data = sector_emissions)
lm_A

summary(lm_A)

# Linear model for B

lm_B <- lm(formula = MC_B ~ Abatement, data = sector_emissions)
lm_B

summary(lm_B)

# Linear model for C

lm_C <- lm(formula =  MC_C ~ Abatement, data = sector_emissions)
lm_C

summary(lm_C)

# Linear model for D

lm_D <- lm(formula = MC_D ~ Abatement, data = sector_emissions)
lm_D

summary(lm_D)


```

```{r}

#Create plots for each of the 4 sectors using their respective abatement cost functions

#Regression line for Sector A

Rline_A <- ggplot(sector_emissions, aes(x = Abatement, y = MC_A)) +
  geom_point()+
  geom_smooth(method = "lm")

Rline_A

#Regression line for Sector B
Rline_B <- ggplot(sector_emissions, aes(x = Abatement, y = MC_B)) +
  geom_point()+
  geom_smooth(method = "lm")

Rline_B

#Regression line for Sector C

Rline_C <- ggplot(sector_emissions, aes(x = Abatement, y = MC_C)) +
  geom_point()+
  geom_smooth(method = "lm")

Rline_C

#Regression line for Sector D

Rline_D <- ggplot(sector_emissions, aes(x = Abatement, y = MC_D)) +
  geom_point()+
  geom_smooth(method = "lm")

Rline_D

```

#2. WTP and Estimating Demand Curves

```{r}

##Find willingness to pay 

WTP_A = lm_A$coefficients[2]*180 + lm_A$coefficients[1]
WTP_A
# Sector A would be willing to pay $95.19 for the first unit

WTP_B = lm_B$coefficients[2]*200 + lm_A$coefficients[1]
WTP_B
# Sector B WTP = 31.10 for for first unit 

WTP_C = lm_A$coefficients[2]*220 + lm_A$coefficients[1]
WTP_C
#Sector C WTP = $118.26 for first unit

WTP_D = lm_A$coefficients[2]*300 + lm_A$coefficients[1]
WTP_D
# Sector D would be willing to pay $164.41 for first unit


```
```{r}

#Derive demand curve for each sector 

#### Sector A

quantity_a <- seq(0,180, by=10) #pick numbers between 0 - 180 in increments of 10 
quantity_a

#Write function for demand curve for section A

slope_a <- lm_A$coefficients[2]
int_a <- lm_A$coefficients[1]
  
  
d_a <- function(q){
  (slope_a*(180-q)) + int_a
}

#Derive demand curve

demand_a <- d_a(quantity_a) #generates y values for each of the x values (given as q)

curve(d_a, from=0, to=180, xlab = "q", ylab = "Price")


```
```{r}
#### Sector B

quantity_b <- seq(0,180, by=10) #pick numbers between 0 - 180 in increments of 10 
quantity_b

#Write function for demand curve for section A
slope_b <- lm_B$coefficients[2]
int_b <- lm_B$coefficients[1]
  
  
d_b <- function(q){
  (slope_b*(180-q)) + int_b
}

#Derive demand curve

demand_b <- d_b(quantity_b) #generates y values for each of the x values (given as q)

curve(d_b, from=0, to=180, xlab = "q", ylab = "Price")


```
```{r}
#### Sector C

quantity_c <- seq(0,180, by=10) #pick numbers between 0 - 180 in increments of 10 
quantity_c

#Write function for demand curve for section A
slope_c <- lm_C$coefficients[2]
int_c <- lm_C$coefficients[1]
  
  
d_c <- function(q){
  (slope_c*(180-q)) + int_c
}

#Derive demand curve

demand_c <- d_c(quantity_c) #generates y values for each of the x values (given as q)

curve(d_c, from=0, to=180, xlab = "q", ylab = "Price")


```

```{r}
#### Sector D

quantity_d <- seq(0,180, by=10) #pick numbers between 0 - 180 in increments of 10 
quantity_d

#Write function for demand curve for section A
slope_d <- lm_D$coefficients[2]
int_d <- lm_D$coefficients[1]
  
  
d_d <- function(q){
  (slope_d*(180-q)) + int_d
}

#Derive demand curve

demand_d <- d_b(quantity_b) #generates y values for each of the x values (given as q)

curve(d_d, from=0, to=180, xlab = "q", ylab = "Price")


```
```{r}
#Plot demand for all sectors

demand_plot <-ggplot(data.frame(x=c(0,200)))+
  stat_function(fun=lm_A, aes(color = "A"))+
  stat_function(fun=lm_B, aes(color = "B"))+
  stat_function(fun=lm_C, aes(color = "C"))+
  stat_function(fun=lm_D, aes(color = "D"))+
  scale_x_continuous(limits = c(0,400), expand = c(0,0))+
  scale_y_continuous(limits = c(0,200), expand = c(0,0))+
  labs(fil = "", 
       color = "Sector", 
       x = "Carbon Demand (in tons of CO2)",
       y = "Price ($/ton)",
       title = "Carbon Emission Demand by Sector")+
  theme_classic() +
  scale_color_manual(values = beyonce_palette(111), name = "Sector", labels = c("A", "B", "C", "D")) +
  theme(plot.title = element_text(hjust = 0.5))
demand_plot









```






3. Find total cost of (a) meeting target in country X, (b) cost/benefit to each sector, (c) tax revenue generated

Part a: Cap on carbon 
```{r}
#Part 1A. Total cost of abatement in country X

# Write abatement curve functions for each sector and set q as 100

#Sector A: 

abate_a <- function(q){
  (slope_a*q) + int_a
}
cost_a_100 <- abate_a(100) # generates the cost of abatement for sector

#Sector B: 

abate_b <- function(q){
  (slope_b*q) + int_b
}
cost_b_100 <- abate_b(100) 

#Sector C: 

abate_c <- function(q){
  (slope_c*q) + int_c
}
cost_c_100 <- abate_c(100) 

# Exclude D because it is not in this country, but we'll define it's abatement curve anyway because we'll need it later in 4

abate_d <- function(q){
  (slope_d*q) + int_d
}

```

```{r}
#Part 2b: Integrate to find the area under the curve (the cost of abatement from 0-100)
areaa_100 <- integrate(abate_a, lower = 0, upper = 100)$value #Cost of abatement for Sector A = $2019.76

areab_100 <- integrate(abate_b, lower = 0, upper = 100)$value #Cost of abatement Sector B = $1925.49

areac_100 <- integrate(abate_c, lower = 0, upper = 100)$value #Cost of abatement Sector C = $2753.63

#Part 3 Add all areas together to find the total cost of abating 100 units from each sector
totalcost_100 <- areaa_100 + areab_100 + areac_100 #Total cost of abatement from sectors A, B, C = $6698.88

##Part 3c. There is no tax revenue with a carbon cap.

```
 

Part 3b. Tax on Carbon

```{r}

# first rearrange supply curves

A_rearrange <- function(y){(1/lm_A$coefficients[2])*(-lm_A$coefficients[1] + y)}

B_rearrange <- function(y){(1/lm_B$coefficients[2])*(-lm_B$coefficients[1] + y)}

C_rearrange <- function(y){(1/lm_C$coefficients[2])*(-lm_C$coefficients[1] + y)}

#ag_supply_country_X2 <- function(y){lm_A_rearrange(y) + lm_B_rearrange(y) + lm_B_rearrange(y)}

ag_intercept <- (-lm_A$coefficients[1]/lm_A$coefficients[2]) + (-lm_B$coefficients[1]/lm_B$coefficients[2]) + (-lm_C$coefficients[1]/lm_C$coefficients[2])

ag_slope <- (1/lm_A$coefficients[2]) + (1/lm_B$coefficients[2]) + (1/lm_C$coefficients[2])

ag_supply_country_X <- function(x){(-ag_intercept/ag_slope) + (x/ag_slope)}

taxprice <- ag_supply_country_X(300)

A_rearrange(taxprice) + B_rearrange(taxprice) + C_rearrange(taxprice)

A_abate <- A_rearrange(taxprice) # 83.33489 #how many tons of carbon they would abate at the tax price, $39.40
B_abate <- B_rearrange(taxprice) # 151.4956
C_abate <- C_rearrange(taxprice) # 65.16953 

A_tax_abatementcost <- integrate(abate_a,lower = 0, upper = A_abate) 

TC_A_tax <- A_tax_abatementcost$value + (180 - A_abate)*taxprice   
#  5093.786 

B_tax_abatementcost <- integrate(abate_b,lower = 0, upper = B_abate) 

TC_B_tax <- B_tax_abatementcost$value + (200 - B_abate)*taxprice   
#  5604.635 

C_tax_abatementcost <- integrate(abate_c,lower = 0, upper = C_abate) 

TC_C_tax <- C_tax_abatementcost$value + (220 - C_abate)*taxprice   
#  7009.365  

TC_country_tax <- TC_C_tax + TC_B_tax + TC_A_tax
#  17707.79

#tax revenue generated

tax_rev <- (180 - A_abate)*taxprice + (200 - B_abate)*taxprice  + (220 - C_abate)*taxprice 
#  11827.97 

```

Part 3c. Cap & Trade
```{r}

TC_A_captrade <- A_tax_abatementcost$value + (100 - A_abate)*taxprice
# 1939.66

TC_B_captrade <- B_tax_abatementcost$value + (100 - B_abate)*taxprice
#  1661.977

TC_C_captrade <- C_tax_abatementcost$value + (100 - C_abate)*taxprice
#  2278.176 

TC_country_captrade <- TC_A_captrade + TC_B_captrade + TC_C_captrade #total cost of all sectors
#  5879.812 

# no tax revenue

#Country A: Needs to buy ~17 credits (16.66511)

#Country B: Could sell 51.4956 credits

#Country C: emitting 154.83047 but only has 120, so they would need to buy 34.83047 credits
```


Question #4
```{r}
A_rearrange <- function(y){(1/lm_A$coefficients[2])*(-lm_A$coefficients[1] + y)}
B_rearrange <- function(y){(1/lm_B$coefficients[2])*(-lm_B$coefficients[1] + y)}
C_rearrange <- function(y){(1/lm_C$coefficients[2])*(-lm_C$coefficients[1] + y)}
D_rearrange <- function(y){(1/lm_D$coefficients[2])*(-lm_D$coefficients[1] + y)}

#ag_supply_country_X2 <- function(y){A_rearrange(y) + B_rearrange(y) + C_rearrange(y)}

ag_intercept_inter <- (-lm_A$coefficients[1]/lm_A$coefficients[2]) + (-lm_B$coefficients[1]/lm_B$coefficients[2]) + (-lm_C$coefficients[1]/lm_C$coefficients[2]) + (-lm_D$coefficients[1]/lm_D$coefficients[2])

ag_slope_inter <- (1/lm_A$coefficients[2]) + (1/lm_B$coefficients[2]) + (1/lm_C$coefficients[2]) + (1/lm_D$coefficients[2])

ag_supply_country_X_Y <- function(x){(-ag_intercept_inter/ag_slope_inter) + (x/ag_slope_inter)}

taxprice_inter <- ag_supply_country_X_Y(300)

A_rearrange(taxprice_inter) + B_rearrange(taxprice_inter) + C_rearrange(taxprice_inter) + D_rearrange(taxprice_inter)

A_abate_inter <- A_rearrange(taxprice_inter) # 66.65079 
B_abate_inter <- B_rearrange(taxprice_inter) # 103.0711
C_abate_inter <- C_rearrange(taxprice_inter) #  52.89119  
D_abate_inter <- D_rearrange(taxprice_inter) # 77.3869 

A_tax_abatementcost_inter <- integrate(abate_a, lower = 0, upper = A_abate_inter) 
#TC_A_tax_inter <- A_tax_abatementcost_inter$value + (cp_A - A_abate_inter)*taxprice_inter  
#  4083.188 

B_tax_abatementcost_inter <- integrate(abate_b, lower = 0, upper = B_abate_inter) 
#TC_B_tax_inter <- B_tax_abatementcost_inter$value + (cp_B - B_abate_inter)*taxprice_inter   
#  4904.803 

C_tax_abatementcost_inter <- integrate(abate_c, lower = 0, upper = C_abate_inter) 
#TC_C_tax_inter <- C_tax_abatementcost_inter$value + (cp_C - C_abate_inter)*taxprice_inter   
#   5460.18 

#TC_country_X_tax_inter <- TC_C_tax_inter + TC_B_tax_inter + TC_A_tax_inter
#   14448.17 

D_abatementcost_inter <- integrate(abate_d, lower = 0, upper = D_abate_inter) 



```

Question 4 Continued
```{r}

TC_A_captrade_inter <- A_tax_abatementcost_inter$value + (100 - A_abate_inter)*taxprice_inter
#  1698.989 

TC_B_captrade_inter <- B_tax_abatementcost_inter$value + (100 - B_abate_inter)*taxprice_inter
#  1924.554 

TC_C_captrade_inter <- C_tax_abatementcost_inter$value + (100 - C_abate_inter)*taxprice_inter
# 1883.88 

TC_D_captrade_inter <- D_abatementcost_inter$value + (0 - D_abate_inter)*taxprice_inter
# -778.3183 

TC_country_X_captradeinter <- TC_A_captrade_inter + TC_B_captrade_inter + TC_C_captrade_inter

#  5507.423 

# the value for country x is a lower cost then under cap and trade for just their country
# no tax revenue

```

Questoin
```{r}

#Question #5

A_emissions <- 180 - A_abate_inter
B_emissions <- 200 - B_abate_inter
C_emissions <- 220 - C_abate_inter
X_emissions <-A_emissions + B_emissions + C_emissions
#  377.3869 
Y_emissions <- 300 - D_abate_inter
#  222.6131 

#a. Country X would have 300 tons of local air pollution in a local cap and trade market
# Country Y would also emit 300 tons becasue that is the cap for that sector

#b In country X, we can find the amount of local air pollution by adding up all the emissions for each sector, which is 377.3869 tons of air pollution; country Y would have 222.6131 tons

#c For country X: Implement the cap and trade program for economic reasons, but this will create more local air pollution. The local air pollution goes up from 300 to 377 if they include country Y in the cap and trade market. So is it worth it?
#Country Y would benefit from joining the cap and trade market with Country X becasue their air pollution goes down from 300 to 222.6131. 

```

